name: C/C++ CI

on:
  push:
    branches: [master, branchMake]
  pull_request:
    branches: [master, branchMake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make


